[2022-02-06 23:11:57,635] {processor.py:163} INFO - Started process (PID=3785) to work on /opt/airflow/dags/data_ingestion_gcs_dags.py
[2022-02-06 23:11:57,675] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dags.py for tasks to queue
[2022-02-06 23:11:57,921] {logging_mixin.py:109} INFO - [2022-02-06 23:11:57,824] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dags.py
[2022-02-06 23:12:29,295] {logging_mixin.py:109} INFO - [2022-02-06 23:12:29,215] {timeout.py:36} ERROR - Process timed out, PID: 3785
[2022-02-06 23:12:30,805] {logging_mixin.py:109} INFO - [2022-02-06 23:12:29,446] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dags.py", line 9, in <module>
    from google.cloud import storage
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 31, in <module>
    from google.cloud.storage._http import Connection
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 21, in <module>
    from google.cloud import _http
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 30, in <module>
    from google.api_core.client_info import ClientInfo
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/client_info.py", line 31, in <module>
    _GRPC_VERSION = pkg_resources.get_distribution("grpcio").version
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 464, in get_distribution
    dist = Requirement.parse(dist)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3139, in parse
    req, = parse_requirements(s)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3084, in parse_requirements
    yield Requirement(line)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3094, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/data_ingestion_gcs_dags.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 3785
[2022-02-06 23:12:47,874] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dags.py
[2022-02-06 23:12:48,388] {processor.py:171} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dags.py took 50.985 seconds
[2022-02-06 23:13:28,863] {processor.py:163} INFO - Started process (PID=3814) to work on /opt/airflow/dags/data_ingestion_gcs_dags.py
[2022-02-06 23:13:28,982] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dags.py for tasks to queue
[2022-02-06 23:13:29,144] {logging_mixin.py:109} INFO - [2022-02-06 23:13:29,143] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dags.py
[2022-02-06 23:14:10,501] {logging_mixin.py:109} INFO - [2022-02-06 23:14:06,867] {timeout.py:36} ERROR - Process timed out, PID: 3814
[2022-02-06 23:14:12,703] {logging_mixin.py:109} INFO - [2022-02-06 23:14:10,524] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dags.py", line 9, in <module>
    from google.cloud import storage
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 33, in <module>
    from google.protobuf import duration_pb2
  File "/home/airflow/.local/lib/python3.7/site-packages/google/protobuf/duration_pb2.py", line 17, in <module>
    DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1egoogle/protobuf/duration.proto\x12\x0fgoogle.protobuf\"*\n\x08\x44uration\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\x42\x83\x01\n\x13\x63om.google.protobufB\rDurationProtoP\x01Z1google.golang.org/protobuf/types/known/durationpb\xf8\x01\x01\xa2\x02\x03GPB\xaa\x02\x1eGoogle.Protobuf.WellKnownTypesb\x06proto3')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/data_ingestion_gcs_dags.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 3814
[2022-02-06 23:14:13,428] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dags.py
[2022-02-06 23:14:14,333] {processor.py:171} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dags.py took 45.559 seconds
[2022-02-06 23:14:57,148] {processor.py:163} INFO - Started process (PID=3840) to work on /opt/airflow/dags/data_ingestion_gcs_dags.py
[2022-02-06 23:14:57,162] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dags.py for tasks to queue
[2022-02-06 23:14:57,168] {logging_mixin.py:109} INFO - [2022-02-06 23:14:57,167] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dags.py
[2022-02-06 23:15:36,587] {logging_mixin.py:109} INFO - [2022-02-06 23:15:35,991] {timeout.py:36} ERROR - Process timed out, PID: 3840
[2022-02-06 23:16:50,629] {processor.py:163} INFO - Started process (PID=3868) to work on /opt/airflow/dags/data_ingestion_gcs_dags.py
[2022-02-06 23:16:50,877] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dags.py for tasks to queue
[2022-02-06 23:16:51,000] {logging_mixin.py:109} INFO - [2022-02-06 23:16:50,951] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dags.py
[2022-02-06 23:17:22,463] {logging_mixin.py:109} INFO - [2022-02-06 23:17:22,463] {timeout.py:36} ERROR - Process timed out, PID: 3868
[2022-02-06 23:17:36,886] {logging_mixin.py:109} INFO - [2022-02-06 23:17:23,782] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dags.py", line 7, in <module>
    from airflow.operators.python import PythonOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 38, in <module>
    from airflow.utils.python_virtualenv import prepare_virtualenv, write_python_script
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1394, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/manager.py", line 496, in _exit_gracefully
    self.log.debug("Current Stacktrace is: %s", '\n'.join(map(str, inspect.stack())))
  File "/usr/local/lib/python3.7/inspect.py", line 1513, in stack
    return getouterframes(sys._getframe(1), context)
  File "/usr/local/lib/python3.7/inspect.py", line 1490, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/usr/local/lib/python3.7/inspect.py", line 1464, in getframeinfo
    lines, lnum = findsource(frame)
  File "/usr/local/lib/python3.7/inspect.py", line 780, in findsource
    module = getmodule(object, file)
  File "/usr/local/lib/python3.7/inspect.py", line 739, in getmodule
    f = getabsfile(module)
  File "/usr/local/lib/python3.7/inspect.py", line 708, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/usr/local/lib/python3.7/inspect.py", line 693, in getsourcefile
    if os.path.exists(filename):
  File "/usr/local/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/data_ingestion_gcs_dags.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 3868
[2022-02-06 23:18:52,619] {processor.py:163} INFO - Started process (PID=3903) to work on /opt/airflow/dags/data_ingestion_gcs_dags.py
[2022-02-06 23:18:52,641] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dags.py for tasks to queue
[2022-02-06 23:18:52,739] {logging_mixin.py:109} INFO - [2022-02-06 23:18:52,650] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dags.py
[2022-02-06 23:19:25,212] {logging_mixin.py:109} INFO - [2022-02-06 23:19:24,657] {timeout.py:36} ERROR - Process timed out, PID: 3903
[2022-02-06 23:19:46,206] {logging_mixin.py:109} INFO - [2022-02-06 23:19:25,337] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dags.py", line 9, in <module>
    from google.cloud import storage
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 37, in <module>
    import grpc
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/__init__.py", line 48, in <module>
    class Future(six.with_metaclass(abc.ABCMeta)):
  File "/home/airflow/.local/lib/python3.7/site-packages/six.py", line 861, in with_metaclass
    class metaclass(type):
  File "/home/airflow/.local/lib/python3.7/site-packages/six.py", line 861, in metaclass
    class metaclass(type):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/data_ingestion_gcs_dags.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 3903
