[2022-02-06 11:02:10,730] {taskinstance.py:1026} INFO - Dependencies not met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2020-03-02T06:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2022-02-06 11:02:11,067] {local_task_job.py:99} INFO - Task is not able to be run
[2022-02-06 21:50:16,285] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2020-03-02T06:00:00+00:00 [queued]>
[2022-02-06 21:50:16,303] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2020-03-02T06:00:00+00:00 [queued]>
[2022-02-06 21:50:16,304] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-06 21:50:16,305] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2022-02-06 21:50:16,306] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-06 21:50:16,322] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2020-03-02 06:00:00+00:00
[2022-02-06 21:50:16,330] {standard_task_runner.py:52} INFO - Started process 1204 to run task
[2022-02-06 21:50:16,340] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2020-03-02T06:00:00+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dags_hw.py', '--cfg-path', '/tmp/tmpqq432k0_', '--error-file', '/tmp/tmp7gaalj7n']
[2022-02-06 21:50:16,343] {standard_task_runner.py:77} INFO - Job 206: Subtask download_dataset_task
[2022-02-06 21:50:16,462] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2020-03-02T06:00:00+00:00 [running]> on host 6aa22590a839
[2022-02-06 21:50:16,513] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-06 21:50:16,547] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2020-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-02T06:00:00+00:00
[2022-02-06 21:50:16,549] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-06 21:50:16,551] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2020-03.csv > /opt/***/yellow_tripdata_2020-03.csv']
[2022-02-06 21:50:16,573] {subprocess.py:85} INFO - Output:
[2022-02-06 21:53:30,084] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-06 21:53:30,167] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20200302T060000, start_date=20220206T215016, end_date=20220206T215330
[2022-02-06 21:53:30,235] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-06 21:53:30,322] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
